name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Tests:
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        node: [14.x, 15.x, 16.x, 17.x, 18.x, 19.x]
        # node: [14.x]
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build Boost
        uses: egor-tensin/build-boost@v1
        id: boost
        with:
          version: 1.81.0
          libraries: filesystem iostreams
          configuration: Release
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Instruct npm to use the local version of node-gyp
        run: npm explore npm/node_modules/@npmcli/run-script -g -- npm_config_global=false npm install node-gyp@latest
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' && matrix.node != '14.x' }}

      - name: Install Dependencies
        run: |
          npm install --no-progress
        env:
          BOOST_ROOT: ${{ steps.boost.outputs.root }}
          BOOST_LIBRARYDIR: ${{ steps.boost.outputs.librarydir }}
          DYLD_LIBRARY_PATH: ${{ steps.boost.outputs.librarydir }}
          LD_LIBRARY_PATH: ${{ steps.boost.outputs.librarydir }}
      - name: Environment Information
        run: npx envinfo
      - name: Run Node tests
        run: |
          install_name_tool -add_rpath ${{ steps.boost.outputs.librarydir }} lib/shared-file-view.node 
          npm test
        env:
          BOOST_ROOT: ${{ steps.boost.outputs.root }}
          BOOST_LIBRARYDIR: ${{ steps.boost.outputs.librarydir }}
          DYLD_LIBRARY_PATH: ${{ steps.boost.outputs.librarydir }}
          LD_LIBRARY_PATH: ${{ steps.boost.outputs.librarydir }}
