name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Tests:
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        #node: [14.x, 15.x, 16.x, 17.x, 18.x, 19.x]
        node: [14.x]
        #os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build Boost
        uses: egor-tensin/build-boost@v1
        id: boost
        with:
          version: 1.81.0
          libraries: filesystem iostreams
          configuration: Release
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          npm install --no-progress
        env:
          BOOST_ROOT: ${{ runner.workspace }}/boost
          BOOST_LIBRARYDIR: ${{ runner.workspace }}/boost
      - name: Environment Information
        run: npx envinfo
      - name: Run Node tests
        run: npm test
